
#
#
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: churchdb_development

staging:
  <<: *default
  database: churchdb_staging

test:
  <<: *default
  database: churchdb_test

production:
  <<: *default
  database: churchdb_production
  username: churchdb
  password: <%= ENV['CHURCHDB_DATABASE_PASSWORD'] %>
